---
# tasks file for roles/dotnet_sdk

- name: Install prerequisites
  ansible.builtin.apt:
    name:
      - wget
      - apt-transport-https
    state: present
    update_cache: yes
  become: yes

- name: Download Microsoft repository package
  ansible.builtin.get_url:
    url: "{{ dotnet_repo_pkg_url }}"
    dest: "/tmp/{{ dotnet_repo_pkg_name }}"
    mode: '0644'

- name: Install Microsoft repository package
  ansible.builtin.apt:
    deb: "/tmp/{{ dotnet_repo_pkg_name }}"
    state: present
  become: yes

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  become: yes

- name: Install .NET SDK 10.0
  ansible.builtin.apt:
    name: dotnet-sdk-10.0
    state: present
  become: yes
