---
# vars file for roles/dotnet_sdk

# URL for the Microsoft package repository
# Using Ubuntu 24.04 (Noble) as a base for Mint in late 2025
dotnet_repo_pkg_url: "https://packages.microsoft.com/config/ubuntu/24.04/packages-microsoft-prod.deb"
dotnet_repo_pkg_name: "packages-microsoft-prod.deb"
